#!/usr/bin/env python3
"""Generate and build a large C extension for the scale scenarios (tests/test_scale.py).

    python gen_large.py OUT_DIR [--functions 15000] [--files 30] [--opt O0] [--jobs 4]

Every extension in the ordinary suite has a handful of functions. This one has as many as
a real project: `seam_large` with FUNCTIONS functions `f00000(a, b)` ... spread over FILES
source files, each exported through its own method table, plus `call_back(fn, arg)` and
`call_each(fn, n)`, which call back into Python. Each function has a few lines of real
code and calls a small helper of its file, so there is something to step over and into.

The sources are written to OUT_DIR/src (the debug info points there) and the module is
built into OUT_DIR/<opt>/seam_large.abi3.so. It uses the stable ABI, as `seamtest` does,
so one build serves every Python version under test.

Line markers are trailing comments, as in the other test extensions: `f00042-first`,
`f00042-body`, `f00042-mix`, `f00042-return` in every function, `mix03-return` in every
file's helper, and `callback-first/call/after/return` in the main file.
"""
import argparse
import concurrent.futures
import os
import subprocess
import sys
import sysconfig

NAME = "seam_large"

HEADER = """\
/* Generated by tests/ext/gen_large.py: %(functions)d functions in %(files)d files. */
#define PY_SSIZE_T_CLEAN
#define Py_LIMITED_API 0x030C0000
#include <Python.h>

%(tables)s
"""

MIX = """\
__attribute__((noinline)) static unsigned long
lg_mix_%(file)02d(unsigned long value, unsigned long salt)
{
    unsigned long mixed = value ^ (salt * 2654435761UL);
    mixed += mixed >> 7;
    return mixed; /* mix%(file)02d-return */
}
"""

# A few shapes of body, so the functions are not all the same code with other constants.
BODIES = [
    """\
    unsigned long acc = (unsigned long)a * %(k1)dUL + (unsigned long)b; /* %(tag)s-body */
    for (long i = 0; i < (b & 7); i++) {
        acc = acc * 31 + (unsigned long)(i ^ %(k2)d);
    }
""",
    """\
    unsigned long cells[4] = {%(k1)dUL, %(k2)dUL, 0, 0}; /* %(tag)s-body */
    cells[2] = (unsigned long)a;
    cells[3] = (unsigned long)b;
    unsigned long acc = 0;
    for (int i = 0; i < 4; i++) {
        acc += cells[i] << i;
    }
""",
    """\
    struct { long low; long high; } range = {a < b ? a : b, a < b ? b : a}; /* %(tag)s-body */
    unsigned long acc = (unsigned long)(range.high - range.low) + %(k1)dUL;
    if (acc %% 3 == 0) {
        acc += %(k2)dUL;
    }
""",
    """\
    const char *label = "%(tag)s"; /* %(tag)s-body */
    unsigned long acc = (unsigned long)(a ^ b);
    while (*label) {
        acc = acc * 131 + (unsigned char)*label++;
    }
""",
]

FUNCTION = """\
static PyObject *
lg_%(tag)s(PyObject *self, PyObject *args)
{
    long a, b;
    if (!PyArg_ParseTuple(args, "ll", &a, &b)) { /* %(tag)s-first */
        return NULL;
    }
%(body)s    acc = lg_mix_%(file)02d(acc, %(k1)dUL); /* %(tag)s-mix */
    return PyLong_FromUnsignedLong(acc & 0xFFFFFFUL); /* %(tag)s-return */
}
"""

MAIN = """\
#include "seam_large.h"

static PyObject *
lg_call_back(PyObject *self, PyObject *args)
{
    PyObject *fn, *arg;
    if (!PyArg_ParseTuple(args, "OO", &fn, &arg)) { /* callback-first */
        return NULL;
    }
    int depth = 1;
    PyObject *res = PyObject_CallFunctionObjArgs(fn, arg, NULL); /* callback-call */
    depth += 1; /* callback-after */
    if (res == NULL) {
        return NULL;
    }
    (void)depth;
    return res; /* callback-return */
}

static PyObject *
lg_call_each(PyObject *self, PyObject *args)
{
    PyObject *fn;
    long count;
    if (!PyArg_ParseTuple(args, "Ol", &fn, &count)) { /* each-first */
        return NULL;
    }
    long total = 0;
    for (long i = 0; i < count; i++) {
        PyObject *res = PyObject_CallFunction(fn, "l", i); /* each-call */
        if (res == NULL) {
            return NULL;
        }
        total += PyLong_AsLong(res);
        Py_DecRef(res);
    }
    return PyLong_FromLong(total); /* each-return */
}

static PyObject *
lg_function_count(PyObject *self, PyObject *noargs)
{
    return PyLong_FromLong(%(functions)d);
}

static PyMethodDef methods[] = {
    {"call_back", lg_call_back, METH_VARARGS, NULL},
    {"call_each", lg_call_each, METH_VARARGS, NULL},
    {"function_count", lg_function_count, METH_NOARGS, NULL},
    {NULL, NULL, 0, NULL},
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT, "seam_large", NULL, -1, methods, NULL, NULL, NULL, NULL,
};

static PyMethodDef *const tables[] = {
%(table_list)s
};

PyMODINIT_FUNC
PyInit_seam_large(void)
{
    PyObject *module = PyModule_Create(&moduledef);
    if (module == NULL) {
        return NULL;
    }
    for (size_t i = 0; i < sizeof(tables) / sizeof(tables[0]); i++) {
        if (PyModule_AddFunctions(module, tables[i]) < 0) {
            return NULL;
        }
    }
    return module;
}
"""


def function_name(index):
    return "f%05d" % index


def source_of(directory, index, functions, files):
    """The source file that holds function number `index`."""
    return os.path.join(directory, "src", "%s_%02d.c" % (NAME, index * files // functions))


def main_source(directory):
    return os.path.join(directory, "src", NAME + "_main.c")


def _write(path, text):
    """Write a file only if its content changed, so an unchanged tree is not rebuilt."""
    try:
        with open(path) as fh:
            if fh.read() == text:
                return
    except OSError:
        pass
    with open(path, "w") as fh:
        fh.write(text)


def generate(directory, functions=15000, files=30):
    """Write the sources under directory/src. Returns the list of .c files."""
    src = os.path.join(directory, "src")
    os.makedirs(src, exist_ok=True)
    per_file = [[] for _ in range(files)]
    for index in range(functions):
        per_file[index * files // functions].append(index)
    sources = []
    for number, indexes in enumerate(per_file):
        parts = ['#include "%s.h"\n' % NAME, MIX % {"file": number}]
        table = ["PyMethodDef %s_methods_%02d[] = {" % (NAME, number)]
        for index in indexes:
            tag = function_name(index)
            values = {"tag": tag, "file": number, "k1": index + 1, "k2": index * 7 + 3}
            parts.append(FUNCTION % dict(values, body=BODIES[index % len(BODIES)] % values))
            table.append('    {"%s", lg_%s, METH_VARARGS, NULL},' % (tag, tag))
        table.append("    {NULL, NULL, 0, NULL},\n};\n")
        path = os.path.join(src, "%s_%02d.c" % (NAME, number))
        _write(path, "\n".join(parts) + "\n" + "\n".join(table))
        sources.append(path)
    _write(os.path.join(src, NAME + ".h"), HEADER % {
        "functions": functions, "files": files,
        "tables": "\n".join("extern PyMethodDef %s_methods_%02d[];" % (NAME, n)
                            for n in range(files))})
    _write(main_source(directory), MAIN % {
        "functions": functions,
        "table_list": "\n".join("    %s_methods_%02d," % (NAME, n) for n in range(files))})
    return sources + [main_source(directory)]


def build(directory, opt="O0", functions=15000, files=30, include=None, jobs=4):
    """Generate (if needed) and build. Returns the directory holding the module."""
    sources = generate(directory, functions, files)
    out_dir = os.path.join(directory, opt)
    out = os.path.join(out_dir, NAME + ".abi3.so")
    os.makedirs(out_dir, exist_ok=True)
    include = include or sysconfig.get_paths()["include"]

    def compile_one(source):
        obj = os.path.join(out_dir, os.path.basename(source)[:-2] + ".o")
        if os.path.exists(obj) and os.path.getmtime(obj) >= os.path.getmtime(source):
            return obj, False
        subprocess.run(["gcc", "-c", "-fPIC", "-g", "-" + opt, "-Wall", "-I", include,
                        source, "-o", obj], check=True)
        return obj, True

    with concurrent.futures.ThreadPoolExecutor(jobs) as pool:
        results = list(pool.map(compile_one, sources))
    if any(changed for _, changed in results) or not os.path.exists(out):
        shared = (["-bundle", "-undefined", "dynamic_lookup"] if sys.platform == "darwin"
                  else ["-shared"])
        subprocess.run(["gcc", *shared, "-o", out] + [obj for obj, _ in results], check=True)
    return out_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("directory")
    parser.add_argument("--functions", type=int, default=15000)
    parser.add_argument("--files", type=int, default=30)
    parser.add_argument("--opt", default="O0", choices=["O0", "O2"])
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--include", help="directory of Python.h (default: this Python's)")
    args = parser.parse_args()
    print(build(args.directory, args.opt, args.functions, args.files, args.include, args.jobs))


if __name__ == "__main__":
    sys.exit(main())
